### PR TITLE
miditorio v2

### PR DESCRIPTION
**Pull request by mgabor3141**

### CODE REVIEW

**Comment by Kronikus** [comment]
image
Unable to import bp from v2 version

**Comment by mgabor3141** [comment]
> Unable to import bp from v2 version

@Kronikus Thanks for letting me know. I have now made it more clear on the site that miditorio v2 only works with Factorio 2.0. Sorry about the confusion.

**Comment by Pheubel** [comment]
Been trying out v2 with the space age DLC and it is crazy how small the footprints are compared to v1, truly a world of difference. 

the one thing that the miditorio converter doesn't do well is when the song has a note that is being held for a while. I don't think there is a silver bullet solution, but would it be possible for the speakers to be offset by the length of the sample being played, minus the tail end, to sort of fake the note being held for longer? i would imagine that it would add a lot more complexity, which might not make it worth it.

**Comment by mgabor3141** [comment]
@Pheubel thanks for your suggestion. This is indeed planned, and have now added #2 to track it.

**Pull request merged**
